title: "Life in Code: My Turing Experience"
email: "rdavid1099@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  A student's perspective of the life, joys and challenges offered by the
  Turing School of Software and Design.
baseurl: ""
url: ""
twitter_username: "ProducerWorkman"
github_username:  "rdavid1099"

markdown: kramdown
theme: minima
